version: '3.4'

services:
  db:
    container_name: db
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    env_file:
      - .env
    links:
      - db
    command: bin/rails server --port 3000 --binding 0.0.0.0
    tty: true
    stdin_open: true
