version: '3.4'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: "postgres:12.1"
    volumes:
      - database-data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  database-data: