# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  # api_key: a1B2c3D4e5F6
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
    region: <%= ENV["AWS_REGION"] %>
    bucket: <%= ENV["AWS_BUCKET"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52ee65adb34e2b53b0dc8d531b4c831570d44889f76301fe916d8a44c013148c4e0c7b6e75938f0a183f03befa7dc170b0be51b899ca7403d19beb137102c94c

test:
  secret_key_base: 5396ffc7268fc52894eb6350486ef82128c338acf219a7d31254e5e3075281d80356ff6fb385c411b161d6d9d2138ea1c624bf7147245aa0bb3ea602c2661c09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
